language: node_js
sudo: false
node_js:
 - 10
install:
  - npm install lerna -g
  - lerna bootstrap
script:  
  - echo ok
deploy:
  provider: npm
  email: "argeopensource@digiturk.com.tr"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    branch: master