language: node_js
sudo: false
node_js:
 - 10
install:
  - npm install lerna -g  
script:  
  - lerna bootstrap
jobs:
  include:
    - stage: cli publish
      node_js: "10"
      script: echo "Deploying cli to npm ..."
      before_deploy: cd packages/cli
      after_deploy: cd ../../
      deploy:
        provider: npm
        email: "argeopensource@digiturk.com.tr"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          branch: master
    - stage: components publish
      node_js: "10"
      script: echo "Deploying components to npm ..."
      before_deploy: cd packages/components
      after_deploy: cd ../../
      deploy:
        provider: npm
        email: "argeopensource@digiturk.com.tr"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          branch: master
    - stage: container publish
      node_js: "10"
      script: echo "Deploying container to npm ..."
      before_deploy: cd packages/container
      after_deploy: cd ../../
      deploy:
        provider: npm
        email: "argeopensource@digiturk.com.tr"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          branch: master
    - stage: ioc publish
      node_js: "10"
      script: echo "Deploying ioc to npm ..."
      before_deploy: cd packages/ioc
      after_deploy: cd ../../
      deploy:
        provider: npm
        email: "argeopensource@digiturk.com.tr"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          branch: master
    - stage: store publish
      node_js: "10"
      script: echo "Deploying store to npm ..."
      before_deploy: cd packages/store
      after_deploy: cd ../../
      deploy:
        provider: npm
        email: "argeopensource@digiturk.com.tr"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          branch: master    
      


